Droit/views/dashboard.py
from flask import Blueprint, render_template
from ..forms import RelocateForm, DeleteForm, QueryForm
from ..models import DirectoryNameToURL

dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/')
@dashboard.route('/home')
@dashboard.route('/directories')
def home():
    """
    Render the home page for the 'dashboard' module
    This returns the names and URLs of adjacent directories
    """
    return render_template("dashboard/directories.html", tagname = 'home', directories = DirectoryNameToURL.objects.all())


@dashboard.route('/query')
def query():
    """
    Render the thing description query page for the 'dashboard' module
    """
    return render_template("dashboard/query.html", tagname = 'query', form = QueryForm())

@dashboard.route('/delete')
def delete():
    """
    Render the thing description deletion page for the 'dashboard' module
    """
    return render_template("dashboard/delete.html", tagname = 'delete', form = DeleteForm())

@dashboard.route('/relocate')
def relocate():
    """
    Render the thing description relocation page for the 'dashboard' module
    """
    return render_template("dashboard/relocate.html", tagname = 'relocate', form = RelocateForm())

@dashboard.route('/script')
def script():
    """
    Render the thing description script query page for the 'dashboard' module
    """
    return render_template("dashboard/script.html", tagname = 'script')

@dashboard.route('/register')
def register():
    """
    Render the thing description register page for the 'dashboard' module
    """
    return render_template('dashboard/register.html', tagname = 'register')

@dashboard.route('/policy')
def policy():
    """
    Render the policy page for the 'dashboard' module
    """
    return render_template('dashboard/policy.html', tagname = 'policy')

@dashboard.route('/policy_decision')
def policy_decision():
    """
    Render the request page for the 'dashboard' module
    """
    return render_template('dashboard/policy_decision.html', tagname = 'policy_decision')

Droit/views/home.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from flask_login import current_user
from ..utils import get_auth_attributes
home = Blueprint('home', __name__)


@home.route('/')
@home.route('/index')
@home.route('/home')
def index():
    """Render the home page for the project

    Returns:
        response: the flask response object representing the HTML page
    """
    return render_template("home/index.html")


@home.route('/about', methods=['GET', 'POST'])
def about():
    """Render the abount page for the project

    Returns:
        response: the flask response object representing the HTML page
    """
    if current_user.is_anonymous:
        # redirect to login page if not logged in
        return redirect(url_for('auth.login'))
    username = current_user.get_username()
    email = current_user.get_email()
    address = current_user.get_address()
    auth_attributes = get_auth_attributes()
    auth_user_attributes = auth_attributes[0]
    if not address:
        address = auth_user_attributes.get('address', None)
    phone_number = current_user.get_phone()
    if not phone_number:
        phone_number = auth_user_attributes.get('phone_number', None)

    policies = []
    for p in current_user.get_policy():
        cur = {'uid': p.get_uid(), 'location': p.get_location(), 'policy_json': p.get_policy_json()}
        policies.append(cur)
    print(policies)
    print(current_user.get_policy())
    return render_template("home/about.html",
                           username=username, email=email, address=address, phone_number=phone_number, policies=policies)


@home.route('/contact')
def contact():
    """Render the contact page for the project

    Returns:
        response: the flask response object representing the HTML page
    """
    return render_template("home/contact.html")


@home.route('/delete_policy')
def policy_decision():

    return render_template('home/about.html', tagname = 'delete_policy')

Droit/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/columbia.ico')}}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
    {% block link %}

    {% endblock%}
    <title>Droit {{ config['HOST_NAME'] }}</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{url_for('home.index')}}">
                <h1>Droit - {{ config['HOST_NAME'] }}</h1>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('home.index')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('dashboard.home')}}">Things</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('home.about')}}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('home.index')}}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.oauth_list')}}">OpenID</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('home.index')}}">Hi, {{current_user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
                    </li>

                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>

    <div class="body">

        {% block body %}

        {% endblock body%}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>

    <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


    {% block script %}
    {% endblock script %}
</body>

</html>