Droit/views/api.py
import json
import copy
import requests
import uuid
import re
import jwt
from flask import Blueprint, request, url_for, redirect, Response, make_response, jsonify, session, render_template
from flask import current_app as app
from flask_login import current_user as user
from py_abac import PDP, AccessRequest, Policy
from urllib.parse import urljoin, urlencode
from ..models import ThingDescription, DirectoryNameToURL, TypeToChildrenNames, TargetToChildName
from ..utils import get_target_url, is_json_request, clean_thing_description, add_policy_to_storage,\
    delete_policy_from_storage, is_policy_request, is_request_allowed, get_auth_attributes, set_auth_user_attr,\
    generate_jwt
from pymongo import MongoClient
from py_abac.storage.mongo import MongoStorage
from ..auth.models import auth_db, Policy
from datetime import datetime

ERROR_JSON = {"error": "Invalid request."}
ERROR_POLICY = {"error": "Invalid policy."}
ERROR_NO_USER = {"error": "Please login."}
OPERATION_COUNT = ""

api = Blueprint('api', __name__)

def delete_local_thing_description(thing_id: str) -> bool:
    """Delete the thing description with the specific 'thing_id' in local directory and return whether the deletion is complete.

    This is the function that perform the real thing description deletion oepration. It will do it locally by deleting the 
    thing description specified by `thing_id` field. If the to-be-delete thing description has publicity larger than 1, it 
    will send addition request to its parent directory to totally remove the record. This is a recursive request and only
    until its finished, this function should return.

    Args:
        thing_id (str): ID for thing description to be deleted

    Return:
        bool: True if the deletion is complete, if any error happens in the whole prcesss, then return False
    """
    delete_thing = ThingDescription.objects(thing_id=thing_id).first()
    if delete_thing is None:
        return True
    delete_thing.delete()
    # 1. if the publicity is larger than 0, it needs to recursively delete the thing in parent's directory
    if delete_thing.publicity > 0:
        delete_up_things(delete_thing.thing_id)
    # 2. if current directory has no other thing_description of this type,
    # should update parent's aggregation information to delete this one
    dir_remaining_count = ThingDescription.objects(
        thing_type=delete_thing.thing_type).count()
    if dir_remaining_count == 0:
        delete_parent_aggregation(
            delete_thing.thing_type, app.config['HOST_NAME'])
    return True


def push_up_things(thing_description: dict, publicity: int) -> bool:
    """Send register request to parent directory, only if the publicity is larger than 0 and current directory has parent

    Args:
        thing_description (dict): the thing description may need to be pushed up
        publicity (int): how many levels the thing needs to be pushed up

    Return:
        bool: boolean value indicating the push up result. If succeed, return True, otherwise False
    """
    parent_directory = DirectoryNameToURL.objects(
        relationship='parent').first()
    # 1. only do push-up when the publicity is larger than 0, and it has parent
    if publicity == 0 or parent_directory is None:
        return True

    # 2. send push up request to the parent url
    parent_url = urljoin(parent_directory.url, url_for('api.register'))
    request_data = {
        "td": thing_description,
        "location": parent_directory.directory_name,
        "publicity": publicity - 1
    }

    response = requests.post(parent_url, data=json.dumps(request_data), headers={
        'Content-Type': 'application/json',
        'Accept-Charset': 'UTF-8'
    })

    return response.status_code == 200


def delete_up_things(thing_id: str) -> bool:
    """Send delete request to parent's directory's /delete API, asking to delete the thing description.
    
    Args:
        thing_id (str): Unique identifer of thing description that specify the thing description to be deleted. 
    Return:
        bool: True if the deletion is complete, otherwise False.
    """
    parent_dir = DirectoryNameToURL.objects(relationship='parent').first()
    response = None
    if parent_dir is not None:
        query_parameters = urlencode(
            {"location": parent_dir.directory_name, "thing_id": thing_id})
        request_url = f"{urljoin(parent_dir.url, url_for('api.delete'))}?{query_parameters}"
        try:
            response = requests.delete(request_url)
        except:
            return False
    return response is None or response.status_code == 200


def add_parent_aggregation(thing_type: str, location: str) -> bool:
    """Send a post request to parent's directory to update the aggregation data.

    Args:
        thing_type(str): Specify the type of the aggregation.
        location(str): the directory name that the aggregation should be using to update.

    Returns:
        bool: True if the update is complete, otherwise False.
    :return: boolean value indicating the update result. return True if update successfully
    """

    parent_dir = DirectoryNameToURL.objects(relationship='parent').first()
    if parent_dir is None:
        return True

    request_body = {"location": location, "thing_type": thing_type}
    request_url = urljoin(parent_dir.url, url_for(
        'api.update_type_aggregation'))

    response = requests.post(request_url, data=json.dumps(request_body), headers={
        'Content-Type': 'application/json',
        'Accept-Charset': 'UTF-8'
    })

    return response.status_code == 200


def delete_parent_aggregation(thing_type: str, location: str) -> bool:
    """Send delete request to parent's [update_type_aggregation] API to update aggregation
    
    Args:
        thing_type (str): The thing type needs to be updated.
        location (str): Which directory name should be removed in the aggregation.

    Returns:
        bool: True when the delete aggregation operation is successful. Otherwise False.
    """
    # 1. if it has no parent directory, terminate the call
    parent_dir = DirectoryNameToURL.objects(relationship='parent').first()
    if parent_dir is None:
        return True
    query_parameters = urlencode(
        {"location": location, "thing_type": thing_type})
    request_url = f"{urljoin(parent_dir.url, url_for('api.update_type_aggregation'))}?{query_parameters}"
    try:
        response = requests.delete(request_url)
    except:
        return False

    return response == 200


def get_children_result(thing_type: str, api: str, query_string: str) -> list:
    """Get thing descriptions from all children directories and return the result

    This operation is done recursively using a DFS serach algorithm. The request is sent to the endpoint of
    children directory specified by `api` argument along with `query_string` as the query parameters. 
    If `thing_type` is specified, then only thing descriptions matching the `thing_type` argument is collected.
    
    Args:
        thing_type(str): Type of thing descriptions to return. Is this is missing, then no filtering will be doing.
        api(str): The API endpoint of the children directories.
        query_string(str): Query string of the of the requests sent to children directories.
    
    Returns:
        list: the list of thing descriptions that meet the filter condition. Each thing description is a dict object.
    """
    children_directories = DirectoryNameToURL.objects(
        relationship='child').all()
    # Get children names that contains only the 'thing_type' accroding to the aggregation stats
    descendant_names_with_type = TypeToChildrenNames.objects(thing_type=thing_type).first() \
        if thing_type is not None else TypeToChildrenNames.objects.first()
    descendant_to_child_mappings = TargetToChildName.objects().all()
    # Send request to each child node that has thing desciriptions with this [thing_type] and get result as a list
    result_list = []
    if children_directories is not None and descendant_names_with_type is not None:
        child_name_to_url_map = {
            child_directory.directory_name: child_directory.url for child_directory in children_directories
        }
        if descendant_to_child_mappings is not None:
            for mapping in descendant_to_child_mappings:
                child_name_to_url_map[mapping.target_name] = child_name_to_url_map[mapping.child_name]

        for descendant_directory_name in descendant_names_with_type.children_names:
            child_url = child_name_to_url_map[descendant_directory_name]
            para_dict = dict(k.split('=') for k in query_string.split('&'))
            if 'location' in para_dict.keys():
                # tmpstr = query_string.split('&', 1)[1]
                # new_query_string = f"location={descendant_directory_name}&{tmpstr}"
                para_dict['location'] = descendant_directory_name
                new_query_string = urlencode(para_dict)
                request_url = f"{urljoin(child_url, api)}?{new_query_string}"
            else:
                request_url = f"{urljoin(child_url, api)}?{query_string}"
            response = requests.get(request_url)
            if response.status_code != 200:
                continue
            child_result = response.json()
            if type(child_result) == list:
                result_list.extend(child_result)
            else:
                result_list.append(child_result)
    return result_list


@api.route('/register', methods=['POST'])
def register():
    """Register thing description at the target location. 

    If the current directory is the target location specified by `location` argument, the operation is processed locally
    Otherwise it will delegate the operation to the next possible directory (if there is ), and return whatever the result it receives
    

Droit/views/dashboard.py
from flask import Blueprint, render_template
from ..forms import RelocateForm, DeleteForm, QueryForm
from ..models import DirectoryNameToURL

dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/')
@dashboard.route('/home')
@dashboard.route('/directories')
def home():
    """
    Render the home page for the 'dashboard' module
    This returns the names and URLs of adjacent directories
    """
    return render_template("dashboard/directories.html", tagname = 'home', directories = DirectoryNameToURL.objects.all())


@dashboard.route('/query')
def query():
    """
    Render the thing description query page for the 'dashboard' module
    """
    return render_template("dashboard/query.html", tagname = 'query', form = QueryForm())

@dashboard.route('/delete')
def delete():
    """
    Render the thing description deletion page for the 'dashboard' module
    """
    return render_template("dashboard/delete.html", tagname = 'delete', form = DeleteForm())

@dashboard.route('/relocate')
def relocate():
    """
    Render the thing description relocation page for the 'dashboard' module
    """
    return render_template("dashboard/relocate.html", tagname = 'relocate', form = RelocateForm())

@dashboard.route('/script')
def script():
    """
    Render the thing description script query page for the 'dashboard' module
    """
    return render_template("dashboard/script.html", tagname = 'script')

@dashboard.route('/register')
def register():
    """
    Render the thing description register page for the 'dashboard' module
    """
    return render_template('dashboard/register.html', tagname = 'register')

@dashboard.route('/policy')
def policy():
    """
    Render the policy page for the 'dashboard' module
    """
    return render_template('dashboard/policy.html', tagname = 'policy')

@dashboard.route('/policy_decision')
def policy_decision():
    """
    Render the request page for the 'dashboard' module
    """
    return render_template('dashboard/policy_decision.html', tagname = 'policy_decision')

Droit/templates/dashboard/dashboard.html
{% extends "layout.html" %}

{% block link %}

{% endblock link %}

{% block body %}

<div class="container-sm dashboard">
  <div class="row sidebar-row">
    <div class="col-md-3 menus list-group">
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'home' else '' }}"
        href="{{ url_for('dashboard.home')}}">
        Directories
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'register' else '' }}"
        href="{{ url_for('dashboard.register') }}">
        Register
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'policy' else '' }}"
        href="{{ url_for('dashboard.policy') }}">
        Policy
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'query' else '' }}"
        href="{{ url_for('dashboard.query')}}">
        Query
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'script' else '' }}"
        href="{{ url_for('dashboard.script')}}">
        Custom Script Query
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'delete' else '' }}"
        href="{{ url_for('dashboard.delete')}}">
        Delete
      </a>
      <a class="list-group-item list-group-item-action {{ 'active' if tagname == 'relocate' else '' }}"
        href="{{ url_for('dashboard.relocate')}}">
        Relocate
      </a>
    </div>

    <div class="col-md-9 main">
      {% block dashboard_content%}
      {% endblock %}
    </div>

  </div>
</div>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">

        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

{% endblock body %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
<script src="{{url_for('static', filename='js/jquery.json-editor.min.js')}}"></script>
{% endblock script%}

Droit/templates/dashboard/delete.html
{% extends "dashboard/dashboard.html" %}


{% block dashboard_content %}
<h2 class="mb-5">Delete Thing</h2>

<form class="delete-form" method="POST" action="{{url_for('api.register')}}">
    <div>
        <div class="form-group">
            {{ form.location.label }}
            {{ form.location(class = 'form-control', id='location', value=config['HOST_NAME']) }}
        </div>
        <div class="form-group">
            {{ form.thing_id.label }}
            {{ form.thing_id(class = 'form-control', id='thing_id') }}
        </div>


        <div class="form-group">
            <button class="btn btn-danger" type="button" id="delete-btn">
                Delete
            </button>

        </div>
    </div>
</form>

{% endblock dashboard_content %}


{% block script %}
{{ super() }}
<script src="{{url_for('static', filename='js/delete.js')}}"></script>
{% endblock script%}

Droit/templates/dashboard/directories.html
{% extends "dashboard/dashboard.html" %}

{% block dashboard_content %}
<h2 class="mb-5">Directories</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Relationship</th>
            <th scope="col">Link</th>
        </tr>
    </thead>
    <tbody>
        {% for directory in directories %}
        <tr>
            <td>{{ directory.directory_name }}</td>
            <td>{{ directory.relationship }}</td>
            <td>
                <a class="btn btn-primary" href="{{  directory.url }}{{url_for('dashboard.home')}}">Go</a>

            </td>
            <td>

            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock dashboard_content%}

Droit/templates/dashboard/policy.html
{% extends "dashboard/dashboard.html" %}

{% block link %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/policy.css')}}">
{% endblock link %}

{% block dashboard_content %}
<h2 class="mb-5">Register New Policy</h2>
<form class="register-form" method="POST" action="{{url_for('api.policy')}}">
  <div class="form-group">
    <label for="json-policydescription">Policy Description(JSON)</label>
    <pre id="json-policydescription"></pre>
  </div>
  <div class="form-group">
    <div class="custom-file">
      <input type="file" class="custom-file-input td-json" id="customFile">
      <label class="custom-file-label td-json" for="customFile">Choose file</label>
    </div>
  </div>
  <div class="form-group">
    <label for="targetLoc">Target Directory</label>
    <input type="text" name="targetLoc" id="targetLoc" class="form-control" value={{config['HOST_NAME']}}>
  </div>
  <div class="form-group">
    <button id="submit" type="button" class="btn btn-primary mt-3">Register</button>
  </div>
</form>

{% endblock dashboard_content %}

{% block script %}
{{ super() }}
<script src="{{url_for('static', filename='js/policyjson.js')}}"></script>
{% endblock script%}

Droit/templates/dashboard/publiclist.html
{% extends "dashboard/dashboard.html" %}

{% block dashboard_content %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Type</th>
      <th scope="col">Publicity</th>
    </tr>
  </thead>
  <tbody>
    {% for td in data.td %}
    <tr>
      <td>{{ td.id }}</td>
      <td>{{ td._type }}</td>
      <td>{{ td.publicity }}</td>
    </tr>
    {% endfor %}    
  </tbody>
</table>

<nav class="">
  <ul class="pagination center-container">
    {% if data.current_page != 1 %}
    <li class="page-item"><a class="page-link" href="{{ url_for('dashboard.get_public_things', page=1) }}">Previous</a></li>
    {% endif %}
    
    {% for page in range(1, data.total_page + 1) %}
      
    {% if page == data.current_page %}
        <li class="page-item disabled"><a class="page-link" href="{{ url_for('dashboard.get_public_things', page=page) }}">{{ page }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for('dashboard.get_public_things', page=page) }}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}
    {% if data.current_page != data.total_page %}
    <li class="page-item"><a class="page-link" href="{{ url_for('dashboard.get_public_things', page=data.current_page + 1) }}">Previous</a></li>
    {% endif %}
    
  </ul>
  <p class="center-text">{{ data.total_page }} Pages in Total</p>
</nav>

{% endblock dashboard_content %}

Droit/templates/dashboard/query.html
{% extends "dashboard/dashboard.html" %}

{% block link %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/query.css')}}">
{% endblock link %}

{% block dashboard_content %}

<h2 class="mb-5">Query</h2>

<form class="register-form" method="POST" action="{{url_for('api.register')}}">
    <div class="form-row align-items-center">
        <div class="col-sm-3">
            <!-- {{ form.location.label }} -->
            {{ form.location(class = 'form-control', id='location', value = config['HOST_NAME'], placeholder = 'Location') }}
        </div>
        <div class="col-sm-3">
            <!-- {{ form.thing_id.label }} -->
            {{ form.thing_id(class = 'form-control', id='thing_id', placeholder = 'Thing ID') }}
        </div>
        <div class="col-sm-3">
            <!-- {{ form.thing_type.label }} -->
            {{ form.thing_type(class = 'form-control', id='thing_type', placeholder = 'Thing Type') }}
        </div>
        <div class="col-sm-auto">
            <button id="search" type="button" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>

<!-- Query result list -->
<div class="result">
    <h2 class="mt-5 mb-5">Query Result</h2>
    <table class="thing-list table">
        <thead>
            <th>Thing ID</th>
            <th>Type</th>
            <th>Title</th>
            <th>Attributes</th>
            <th>Show Detail</th>
            <th>JWT</th>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>

<!-- Modal for thing description detail -->
<div class="modal fade" id="thing_description_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="thing_description_modal_title">Thing Description Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <pre id="json-thingdescription"></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal for jwt description detail -->
<div class="modal fade" id="jwt_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="jwt_modal_title">JWT Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <pre id="json-jwt"></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock dashboard_content %}


{% block script %}
{{ super() }}
<script src="{{url_for('static', filename='js/query.js')}}"></script>
{% endblock script%}

Droit/templates/dashboard/register.html
{% extends "dashboard/dashboard.html" %}

{% block link %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}">
{% endblock link %}

{% block dashboard_content %}
<h2 class="mb-5">Register New Thing</h2>

<form class="register-form" method="POST" action="{{url_for('api.register')}}">
  <div class="form-group">
    <label for="json-thingdescription">Thing Description(JSON)</label>
    <pre id="json-thingdescription"></pre>
  </div>
  <div class="form-group">
    <div class="custom-file">
      <input type="file" class="custom-file-input td-json" id="customFile">
      <label class="custom-file-label td-json" for="customFile">Choose file</label>
    </div>
  </div>
  <div class="form-group">
    <label for="targetLoc">Target Directory</label>
    <input type="text" name="targetLoc" id="targetLoc" class="form-control" value={{config['HOST_NAME']}}>
  </div>
  <div class="form-group">
    <label for="publicity">Publicity</label>
    <input type="number" name="publicity" id="publicity" class="form-control" min="0" value="0">
  </div>

  <div class="form-group">
    <button id="submit" type="button" class="btn btn-primary mt-3">Register</button>
  </div>
</form>

{% endblock dashboard_content %}

{% block script %}
{{ super() }}
<script src="{{url_for('static', filename='js/registerjson.js')}}"></script>
{% endblock script%}

Droit/templates/dashboard/relocate.html
{% extends "dashboard/dashboard.html" %}

{% block dashboard_content %}
<h2 class="mb-5">Relocate Thing</h2>

<form class="register-form" method="POST" action="{{url_for('api.register')}}">
    <div>
        <div class="form-group">
            {{ form.from_location.label }}
            {{ form.from_location(class = 'form-control', id='from_location', value=config['HOST_NAME']) }}
        </div>
        <div class="form-group">
            {{ form.to_location.label }}
            {{ form.to_location(class = 'form-control', id='to_location') }}
        </div>
        <div class="form-group">
            {{ form.thing_id.label }}
            {{ form.thing_id(class = 'form-control', id='thing_id') }}
        </div>
        <div class="form-group">
            <button id="relocate-btn" type="button" class="btn btn-warning">
                Relocate
            </button>
        </div>
    </div>
</form>

{% endblock dashboard_content %}


{% block script %}
{{ super() }}
<script src="{{url_for('static', filename='js/relocate.js')}}"></script>
{% endblock script%}

Droit/templates/dashboard/request.html
{% extends "dashboard/dashboard.html" %}

{% block link %}
{{ super() }}
<!-- <link rel="stylesheet" href="{{url_for('static', filename='css/policy.css')}}"> -->
{% endblock link %}

{% block dashboard_content %}

{% if current_user.is_authenticated %}
  Hi {{ current_user.name }}!
{% endif %}

{% endblock dashboard_content %}

{% block script %}
{{ super() }}
<!-- <script src="{{url_for('static', filename='js/policyjson.js')}}"></script> -->
{% endblock script%}

Droit/templates/dashboard/script.html
{% extends "dashboard/dashboard.html" %}

{% block link %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/script.css')}}">
{% endblock link %}

{% block dashboard_content %}
<h2 class="mb-5">Custom Script Query</h2>

<form class="register-form" method="POST" action="{{url_for('api.register')}}">
  <div>
    <div class="form-group">
      <pre id="json-query-script"></pre>
    </div>
    <div class="form-group">
      <button id="search" type="button" class="btn btn-primary">Search</button>
    </div>
  </div>
</form>

<!-- Query result list -->
<div class="result">
  <h2 class="mt-5 mb-5">Query Result</h2>
  <table class="table">
      <thead>
          <th>Aggregation Type</th>
          <th>Result</th>
      </thead>
      <tbody>

      </tbody>
  </table>
</div>

{% endblock dashboard_content %}


{% block script %}
{{ super() }}
<script src="{{url_for('static', filename='js/script.js')}}"></script>
{% endblock script%}